module.exports = {
  ARSafari: "AR Safari",
  AsteroidTrapeze: "Asteroid Trapeze",
  BuildABot: "Build-A-Bot",
  Cantina: "Cantina",
  Casino: "Casino",
  CaveDiving: "Cave Diving",
  CentrifugeGym: "Centrifuge Gym",
  ContinentalBreakfast: "Continental Breakfast",
  CraterCanyoneering: "Crater Canyoneering",
  CryoSpa: "Cryo Spa",
  DeepSeaExploration: "Deep Sea Exploration",
  DeepSpaceMassage: "Deep Space Massage",
  ExtracontinentalBreakfast: "Extracontinental Breakfast",
  ExoskeletonDemos: "Exoskeleton Demos",
  GeneTherapy: "Gene Therapy",
  GeothermalBaths: "Geothermal Baths",
  GrowAClone: "Grow-A-Clone",
  HologramTeleconferencing: "Hologram Teleconferencing",
  HydroponicGardens: "Hydroponic Gardens",
  KidFriendly: "Good for Kids",
  LaserTag: "Laser Tag",
  OrbitalZiplining: "Orbital Ziplining",
  OxygenBar: "Oxygen Bar",
  PetFriendly: "Pet Friendly",
  PrimordialOozeSampling: "Primordial Ooze Sampling",
  QuantumBungee: "Quantum Bungee Jumping",
  Refueling: "Refueling Station",
  RobotRepairs: "Robot Repairs",
  RoverRentals: "Rover Rentals",
  ScienceBase: "Science Base",
  SpaceshipRentals: "Spaceship Rentals",
  SubAtomicMagic: "Subatomic Magic Shows",
  SwimmingPool: "Swimming Pool",
  TerraformingMuseum: "Terraforming Museum",
  VolcanicSpelunking: "Volcanic Spelunking",
  VRBattleArena: "VR Battle Arena",
  ZeroGravity: "Zero Gravity"
}
